### ISSUE TITLE
기간으로 검색했을 때 처리방법

### ISSUE THREAD

**Issue by seyoung0314** [project-egg/festival#16]
기간으로 검색하면

처음에 의견모았던건 월별로 누르면 바로 검색되게 하기로 했었는데
데이터가 내년 1월까지 밖에 없어서 좀 날짜 옵션이 너무 한정적일 것 같아요. (2024-11,12,2025-01 세개뿐이라)

그래서 만약에 일별로 선택가능하도록 변경하면 고민해봐야 할 부분이

1. [2024-11-01] ~ [2024-11-20]  이런식으로 날짜 표시를 두 부분으로 잡아야 할 지
1-1. 두 부분으로 잡는다면 검색버튼이 있는게 좋을 것 같은데 어떠신가요

2. [2024-11-01] 이렇게 시작일만 검색되게 할 지
 
어떤게 좋으신 지 의견달아주세요~~

**Comment by inhyeokoh** [comment]
시작일을 매월 1일로 고정시키는건 좀 이상할 거 같아요
기능 구현 가능하시면 시작일 종료일 선택 가능한 전자 방법이 좋을 거 같습니다.
